[build]
  base = "frontend"
  command = "npm install --legacy-peer-deps; npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"
  VITE_API_URL = "https://sauvegarde-mai-gestion-production.up.railway.app/api"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "*.js"
  [headers.values]
    Content-Type = "application/javascript; charset=utf-8"

[[headers]]  
  for = "*.mjs"
  [headers.values]
    Content-Type = "application/javascript; charset=utf-8"